name: Validar Shell Script

on:
  push:
    branches: [ "main" ]  # Ejecutar solo en push a la rama main

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Validar script.sh
        run: shellcheck script.sh